      D I S C L A I M E R      -------------------     The files contained in th
is PDS are FREEWARE. Use at your own    risk.  Neither Mark Zelden, nor other co
ntributing organizations    or individuals accept any liability of any kind hows
oever    arising out of the use of these files. You are free to use and    modif
y these files as you desire, however, the author does ask    that you leave his
name in the files and give credit to him as    the original programmer.
